name: example
description: an example
publish_to: none
version: 0.0.1+1

environment:
  flutter: ">=2.0.0 <3.0.0"
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_persistent_queue:
    path: ../

flutter:
  uses-material-design: true
